import { Booking, BusSchedule, User, Bus, BusCompany, Route } from '../models';
import SocketServer from '../config/socket';

export class BookingService {
  static async createBooking(
    userId: number,
    bookingData: {
      schedule_id: number;
      travel_date: Date;
      seat_number: number;
    }
  ) {
    const { schedule_id, travel_date, seat_number } = bookingData;

    // Validate schedule exists
    const schedule = await BusSchedule.findByPk(schedule_id, {
      include: [
        {
          model: Bus,
          as: 'bus',
          attributes: ['total_seats'],
        },
      ],
    });

    if (!schedule) {
      throw new Error('Schedule not found');
    }

    // Check if seat is available
    const existingBooking = await Booking.findOne({
      where: {
        schedule_id,
        travel_date,
        seat_number,
        status: 'confirmed',
      },
    });

    if (existingBooking) {
      throw new Error('Seat is not available');
    }

    // Create booking (booking_code will be auto-generated by hooks)
    const booking = await Booking.create({
      user_id: userId,
      schedule_id,
      travel_date,
      seat_number,
      status: 'confirmed',
    });

    // Reload booking to get the final booking code generated by afterCreate hook
    await booking.reload();

    // Get full booking details
    const fullBooking = await this.getBookingById(booking.id);

    // Emit real-time events
    try {
      const socketServer = SocketServer.getInstance();
      socketServer.emitBookingCreated({
        ...fullBooking.toJSON(),
        user_id: userId,
        schedule_id,
        travel_date,
      });

      // Get updated seat availability
      const availableSeats = await this.getAvailableSeatsForSchedule(
        schedule_id,
        travel_date.toString()
      );

      // Emit seat availability update
      socketServer.emitSeatAvailability(
        schedule_id,
        travel_date.toString(),
        availableSeats.available_seats
      );

      // Emit low seat warning if applicable
      const totalSeats = (schedule as any).bus.total_seats;
      const remainingSeats = availableSeats.total_available;
      const occupancyRate = ((totalSeats - remainingSeats) / totalSeats) * 100;

      if (occupancyRate >= 80) {
        socketServer.emitLowSeatWarning(
          schedule_id,
          travel_date.toString(),
          remainingSeats
        );
      }
    } catch (error) {
      console.error('Error emitting real-time events:', error);
      // Don't fail the booking if real-time notification fails
    }

    return fullBooking;
  }

  static async getUserBookings(userId: number) {
    return await Booking.findAll({
      where: { user_id: userId },
      include: [
        {
          model: BusSchedule,
          as: 'schedule',
          include: [
            {
              model: Bus,
              as: 'bus',
              attributes: ['plate_number'],
              include: [
                {
                  model: BusCompany,
                  as: 'company',
                  attributes: ['name'],
                },
              ],
            },
            {
              model: Route,
              as: 'route',
              attributes: ['departure_city', 'arrival_city'],
            },
          ],
        },
      ],
      order: [['travel_date', 'DESC'], ['created_at', 'DESC']],
    });
  }

  static async getBookingByCode(code: string) {
    const booking = await Booking.findOne({
      where: { booking_code: code },
      include: [
        {
          model: User,
          as: 'user',
          attributes: ['full_name', 'email', 'phone_number'],
        },
        {
          model: BusSchedule,
          as: 'schedule',
          include: [
            {
              model: Bus,
              as: 'bus',
              attributes: ['plate_number'],
              include: [
                {
                  model: BusCompany,
                  as: 'company',
                  attributes: ['name'],
                },
              ],
            },
            {
              model: Route,
              as: 'route',
              attributes: ['departure_city', 'arrival_city'],
            },
          ],
        },
      ],
    });

    if (!booking) {
      throw new Error('Booking not found');
    }

    return booking;
  }

  static async getAllBookings() {
    return await Booking.findAll({
      include: [
        {
          model: User,
          as: 'user',
          attributes: ['full_name', 'email', 'phone_number'],
        },
        {
          model: BusSchedule,
          as: 'schedule',
          include: [
            {
              model: Bus,
              as: 'bus',
              attributes: ['plate_number'],
              include: [
                {
                  model: BusCompany,
                  as: 'company',
                  attributes: ['name'],
                },
              ],
            },
            {
              model: Route,
              as: 'route',
              attributes: ['departure_city', 'arrival_city'],
            },
          ],
        },
      ],
      order: [['created_at', 'DESC']],
    });
  }

  static async cancelBooking(userId: number, code: string) {
    const booking = await Booking.findOne({
      where: {
        booking_code: code,
        user_id: userId,
        status: 'confirmed',
      },
    });

    if (!booking) {
      throw new Error('Booking not found or already cancelled');
    }

    await booking.update({ status: 'cancelled' });

    // Emit real-time events
    try {
      const socketServer = SocketServer.getInstance();
      socketServer.emitBookingCancelled({
        ...booking.toJSON(),
        user_id: userId,
      });

      // Get updated seat availability
      const availableSeats = await this.getAvailableSeatsForSchedule(
        booking.schedule_id,
        booking.travel_date.toString()
      );

      // Emit seat availability update
      socketServer.emitSeatAvailability(
        booking.schedule_id,
        booking.travel_date.toString(),
        availableSeats.available_seats
      );
    } catch (error) {
      console.error('Error emitting real-time events:', error);
    }

    return booking;
  }

  static async updateBookingStatus(
    id: number,
    status: 'confirmed' | 'cancelled' | 'completed'
  ) {
    const booking = await Booking.findByPk(id);
    if (!booking) {
      throw new Error('Booking not found');
    }

    await booking.update({ status });

    // Emit real-time notification to the user
    try {
      const socketServer = SocketServer.getInstance();
      socketServer.sendNotificationToUser(booking.user_id, {
        type: 'booking:status:updated',
        title: 'Booking Status Updated',
        message: `Your booking ${booking.booking_code} status has been updated to ${status}`,
        data: {
          bookingCode: booking.booking_code,
          status,
        },
      });
    } catch (error) {
      console.error('Error emitting real-time notification:', error);
    }

    return booking;
  }

  private static async getBookingById(id: number) {
    const booking = await Booking.findByPk(id, {
      include: [
        {
          model: User,
          as: 'user',
          attributes: ['full_name', 'email', 'phone_number'],
        },
        {
          model: BusSchedule,
          as: 'schedule',
          include: [
            {
              model: Bus,
              as: 'bus',
              attributes: ['plate_number'],
              include: [
                {
                  model: BusCompany,
                  as: 'company',
                  attributes: ['name'],
                },
              ],
            },
            {
              model: Route,
              as: 'route',
              attributes: ['departure_city', 'arrival_city'],
            },
          ],
        },
      ],
    });

    if (!booking) {
      throw new Error('Booking not found');
    }

    return booking;
  }

  private static async getAvailableSeatsForSchedule(
    scheduleId: number,
    travelDate: string
  ) {
    const schedule = await BusSchedule.findByPk(scheduleId, {
      include: [
        {
          model: Bus,
          as: 'bus',
          attributes: ['total_seats'],
        },
      ],
    });

    if (!schedule) {
      throw new Error('Schedule not found');
    }

    const bookedSeats = await Booking.findAll({
      where: {
        schedule_id: scheduleId,
        travel_date: travelDate,
        status: 'confirmed',
      },
      attributes: ['seat_number'],
    });

    const booked = bookedSeats.map((b) => b.seat_number);
    const totalSeats = (schedule as any).bus.total_seats;
    const allSeats = Array.from({ length: totalSeats }, (_, i) => i + 1);
    const availableSeats = allSeats.filter((seat) => !booked.includes(seat));

    return {
      schedule_id: scheduleId,
      travel_date: travelDate,
      available_seats: availableSeats,
      total_available: availableSeats.length,
    };
  }
}